---
apiVersion: v1
kind: Secret
metadata:
  namespace: monitoring
  name: objstore
stringData:
  objstore.yml: |-
    type: S3
    config:
      bucket: prometheus-metrics
      endpoint: "minio.minio:9000"
      insecure: true
      access_key: "WN5q73zyxDIiJNRa"
      secret_key: "CM6qwcgGdU2o4WYGBHpcHN2e4dACXeDd"
