apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nodejs-smon
  labels:
    app: nodejs-app

### Default labels for Prometheus Grafana stack ###
    #release: prometheus

  namespace: demo
spec:
  endpoints:
  - port: nodejs-port
    path: /metrics
    interval: 15s

 # namespaceSelector:
 #   matchNames:
 #   - demo1

  selector:
    matchLabels:
      app: nodejs-app

### Default labels for Prometheus Grafana stack ###
      #release: prometheus

  targetLabels:
  - nodejs-app
