apiVersion: v1
kind: Service
metadata:
  name: nodejs-svc
  labels:
    app: nodejs-app

### Default labels for Prometheus Grafana stack ###
    #release: prometheus

  namespace: demo
spec:
  selector:
    app: nodejs-app

### Default labels for Prometheus Grafana stack ###
    #release: prometheus

  type: NodePort
  ports:
  - name: nodejs-port
    port: 8081
    targetPort: nodejs-port
