apiVersion: v1
kind: Service
metadata:
  name: python-svc
  labels:
    app: python-app
  namespace: demo
spec:
  type: ClusterIP
  selector:
    app: python-app
  ports:
    - protocol: TCP
      name: python-app-port
      port: 80
      targetPort: 5000
