apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: python-smon
  labels:
    app: python-app
  namespace: demo
spec:
  endpoints:
  - interval: 30s
    port: python-app-port
    path: /metrics
  selector:
    matchLabels:
      app: python-app
  targetLabels:
  - python-app
