apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  labels:
    app: python-app
  namespace: demo
spec:
  selector:
    matchLabels:
      app: python-app
  replicas: 1
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python
        image: aimvector/python:metrics
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
