apiVersion: v1
kind: Service
metadata:
  name: spring-svc
  labels:
    app: spring-app
  namespace: demo
spec:
  type: ClusterIP
  selector:
    app: spring-app
  ports:
    - protocol: TCP
      name: spring-port
      port: 8080
      targetPort: 8080
