apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  labels:
    app: spring-app
  namespace: demo
spec:
  selector:
    matchLabels:
      app: spring-app
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: spring
        image: docker.io/nirvanarsc/my-app
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
